# Generated by Django 6.1 on 2026-08-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeanalysis'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_SKill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_links', to='skills.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resume', 'skill'), name='unique_resume_skill')],
            },
        ),
    ]
